"""
ReportGenerator - Generates markdown reports from findings.

This tool creates human-readable and structured reports from findings
for runbook consumption and end-user delivery.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime, timezone


class ReportGenerator:
    """
    Report generation tool for creating markdown reports from findings.
    
    Supports multiple report formats:
    - Executive summary
    - Technical detailed report
    - Vulnerability-focused report
    - Technology inventory report
    """
    
    def __init__(self):
        """Initialize the ReportGenerator."""
        pass
    
    def generate_executive_summary(
        self,
        mission_id: int,
        findings: List[Dict[str, Any]],
        mission_metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generate an executive summary report.
        
        Args:
            mission_id: Mission ID
            findings: List of findings to summarize
            mission_metadata: Optional metadata (target URL, start time, etc.)
            
        Returns:
            Markdown-formatted executive summary
        """
        metadata = mission_metadata or {}
        target = metadata.get('target_url', 'Unknown')
        started_at = metadata.get('started_at', 'Unknown')
        
        # Calculate statistics
        total = len(findings)
        by_severity = self._count_by_field(findings, 'severity')
        by_type = self._count_by_field(findings, 'finding_type')
        
        # Generate report
        lines = [
            "# Executive Summary",
            f"\n**Mission ID:** {mission_id}",
            f"**Target:** {target}",
            f"**Assessment Date:** {started_at}",
            f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "\n## Overview",
            f"\nThis assessment identified **{total} findings** across the target application.",
            "\n## Findings by Severity",
            ""
        ]
        
        for severity in ['critical', 'high', 'medium', 'low', 'info']:
            count = by_severity.get(severity, 0)
            if count > 0:
                emoji = {'critical': '🔴', 'high': '🟠', 'medium': '🟡', 'low': '🔵', 'info': '⚪'}.get(severity, '⚪')
                lines.append(f"- {emoji} **{severity.upper()}**: {count}")
        
        lines.extend([
            "\n## Finding Categories",
            ""
        ])
        
        # Top 5 categories
        sorted_types = sorted(by_type.items(), key=lambda x: x[1], reverse=True)
        for finding_type, count in sorted_types[:5]:
            lines.append(f"- **{finding_type}**: {count}")
        
        # Key findings
        high_severity = [f for f in findings if f.get('severity', '').lower() in ['critical', 'high']]
        if high_severity:
            lines.extend([
                "\n## Key Findings",
                ""
            ])
            for finding in high_severity[:5]:  # Top 5
                title = finding.get('title', 'Untitled')
                severity = finding.get('severity', 'unknown').upper()
                lines.append(f"- **[{severity}]** {title}")
        
        # Recommendations
        lines.extend([
            "\n## Recommendations",
            ""
        ])
        
        if by_severity.get('critical', 0) > 0:
            lines.append("1. **Immediate action required**: Address critical vulnerabilities immediately")
        if by_severity.get('high', 0) > 0:
            lines.append(f"2. **High priority**: Remediate {by_severity['high']} high-severity findings")
        if by_type.get('tech_fingerprint', 0) > 5:
            lines.append("3. **Review exposure**: Multiple technologies detected - minimize attack surface")
        
        lines.append("\n---\n*Report generated by AI-Hunter Autonomous Security Testing Platform*")
        
        return '\n'.join(lines)
    
    def generate_technical_report(
        self,
        mission_id: int,
        findings: List[Dict[str, Any]],
        mission_metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generate a detailed technical report.
        
        Args:
            mission_id: Mission ID
            findings: List of findings
            mission_metadata: Optional metadata
            
        Returns:
            Markdown-formatted technical report
        """
        metadata = mission_metadata or {}
        target = metadata.get('target_url', 'Unknown')
        
        lines = [
            "# Technical Security Assessment Report",
            f"\n**Mission ID:** {mission_id}",
            f"**Target:** {target}",
            f"**Report Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "\n---",
            "\n## Table of Contents",
            "\n1. [Assessment Summary](#assessment-summary)",
            "2. [Detailed Findings](#detailed-findings)",
            "3. [Technology Stack](#technology-stack)",
            "4. [Appendix](#appendix)",
            "\n---",
            "\n## Assessment Summary",
            f"\nThis report documents the findings from an automated security assessment of {target}.",
            f"A total of **{len(findings)} findings** were identified during this assessment.",
            "\n### Findings Distribution",
            ""
        ]
        
        # Severity breakdown
        by_severity = self._count_by_field(findings, 'severity')
        lines.append("\n| Severity | Count |")
        lines.append("|----------|-------|")
        for severity in ['critical', 'high', 'medium', 'low', 'info']:
            count = by_severity.get(severity, 0)
            lines.append(f"| {severity.upper()} | {count} |")
        
        # Detailed findings
        lines.extend([
            "\n---",
            "\n## Detailed Findings",
            ""
        ])
        
        # Group by severity
        for severity in ['critical', 'high', 'medium', 'low', 'info']:
            severity_findings = [f for f in findings if f.get('severity', '').lower() == severity]
            if severity_findings:
                lines.append(f"\n### {severity.upper()} Severity Findings")
                lines.append("")
                
                for i, finding in enumerate(severity_findings, 1):
                    title = finding.get('title', 'Untitled Finding')
                    finding_type = finding.get('finding_type', 'unknown')
                    description = finding.get('description', 'No description available')
                    
                    lines.extend([
                        f"\n#### {i}. {title}",
                        f"\n**Type:** {finding_type}",
                        f"**Severity:** {severity.upper()}",
                        f"\n**Description:**",
                        f"\n{description}",
                        ""
                    ])
                    
                    # Add details if available
                    details = finding.get('details', {})
                    if details and isinstance(details, dict):
                        lines.append("\n**Additional Details:**")
                        for key, value in details.items():
                            if isinstance(value, (str, int, float, bool)):
                                lines.append(f"- **{key}:** {value}")
        
        # Technology stack
        tech_findings = [f for f in findings if 'tech' in f.get('finding_type', '').lower() or 'fingerprint' in f.get('finding_type', '').lower()]
        if tech_findings:
            lines.extend([
                "\n---",
                "\n## Technology Stack",
                "\nThe following technologies were identified:",
                ""
            ])
            
            for finding in tech_findings:
                details = finding.get('details', {})
                if isinstance(details, dict):
                    tech_name = details.get('technology') or details.get('name') or finding.get('title')
                    version = details.get('version', 'unknown')
                    lines.append(f"- **{tech_name}** (v{version})")
        
        # Appendix
        lines.extend([
            "\n---",
            "\n## Appendix",
            "\n### Methodology",
            "\nThis assessment was conducted using the AI-Hunter autonomous security testing platform.",
            "The platform combines automated reconnaissance, vulnerability scanning, and intelligent analysis.",
            "\n### Disclaimer",
            "\nThis report is generated by an automated system. Findings should be validated by security professionals",
            "before taking remediation actions. False positives may occur.",
            "\n---",
            "\n*End of Report*"
        ])
        
        return '\n'.join(lines)
    
    def generate_vulnerability_report(
        self,
        mission_id: int,
        findings: List[Dict[str, Any]],
        focus_types: Optional[List[str]] = None
    ) -> str:
        """
        Generate a vulnerability-focused report.
        
        Args:
            mission_id: Mission ID
            findings: List of findings
            focus_types: Optional list of vulnerability types to focus on
            
        Returns:
            Markdown-formatted vulnerability report
        """
        # Filter for vulnerabilities
        vuln_findings = [
            f for f in findings 
            if 'vulnerability' in f.get('finding_type', '').lower() 
            or f.get('severity', '').lower() in ['critical', 'high']
        ]
        
        # Further filter by focus types if specified
        if focus_types:
            vuln_findings = [
                f for f in vuln_findings
                if any(ft.lower() in f.get('finding_type', '').lower() for ft in focus_types)
            ]
        
        lines = [
            "# Vulnerability Assessment Report",
            f"\n**Mission ID:** {mission_id}",
            f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"\n**Total Vulnerabilities:** {len(vuln_findings)}",
            "\n---",
            "\n## Critical & High Severity Vulnerabilities",
            ""
        ]
        
        # Critical vulnerabilities
        critical = [f for f in vuln_findings if f.get('severity', '').lower() == 'critical']
        if critical:
            lines.append(f"\n### 🔴 CRITICAL ({len(critical)})")
            lines.append("")
            for vuln in critical:
                self._add_vulnerability_detail(lines, vuln)
        
        # High vulnerabilities
        high = [f for f in vuln_findings if f.get('severity', '').lower() == 'high']
        if high:
            lines.append(f"\n### 🟠 HIGH ({len(high)})")
            lines.append("")
            for vuln in high:
                self._add_vulnerability_detail(lines, vuln)
        
        # Medium vulnerabilities (summary only)
        medium = [f for f in vuln_findings if f.get('severity', '').lower() == 'medium']
        if medium:
            lines.extend([
                f"\n### 🟡 MEDIUM ({len(medium)})",
                "\nMedium severity vulnerabilities detected. See technical report for details.",
                ""
            ])
        
        # Remediation priorities
        lines.extend([
            "\n---",
            "\n## Remediation Priorities",
            ""
        ])
        
        if critical:
            lines.append(f"1. **IMMEDIATE:** Address {len(critical)} critical vulnerabilities")
        if high:
            lines.append(f"2. **HIGH PRIORITY:** Remediate {len(high)} high-severity vulnerabilities")
        if medium:
            lines.append(f"3. **MEDIUM PRIORITY:** Review {len(medium)} medium-severity findings")
        
        lines.append("\n---\n*This report should be reviewed by qualified security personnel*")
        
        return '\n'.join(lines)
    
    def _add_vulnerability_detail(self, lines: List[str], vuln: Dict[str, Any]) -> None:
        """Helper to add vulnerability details to report."""
        title = vuln.get('title', 'Untitled Vulnerability')
        vuln_type = vuln.get('finding_type', 'unknown')
        description = vuln.get('description', 'No description')
        
        lines.extend([
            f"\n#### {title}",
            f"\n**Type:** {vuln_type}",
            f"\n{description}",
            ""
        ])
        
        # Add remediation if available
        details = vuln.get('details', {})
        if isinstance(details, dict) and 'remediation' in details:
            lines.append(f"**Recommended Action:** {details['remediation']}")
            lines.append("")
    
    def generate_technology_inventory(
        self,
        mission_id: int,
        findings: List[Dict[str, Any]]
    ) -> str:
        """
        Generate a technology inventory report.
        
        Args:
            mission_id: Mission ID
            findings: List of findings
            
        Returns:
            Markdown-formatted technology inventory
        """
        tech_findings = [
            f for f in findings 
            if 'tech' in f.get('finding_type', '').lower() 
            or 'fingerprint' in f.get('finding_type', '').lower()
        ]
        
        lines = [
            "# Technology Stack Inventory",
            f"\n**Mission ID:** {mission_id}",
            f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"\n**Technologies Detected:** {len(tech_findings)}",
            "\n---",
            "\n## Detected Technologies",
            "\n| Technology | Version | Category | Notes |",
            "|------------|---------|----------|-------|"
        ]
        
        for finding in tech_findings:
            details = finding.get('details', {})
            if isinstance(details, dict):
                tech_name = details.get('technology') or details.get('name') or finding.get('title', 'Unknown')
                version = details.get('version', 'N/A')
                category = details.get('category', 'Unknown')
                notes = details.get('confidence', 'N/A')
                
                lines.append(f"| {tech_name} | {version} | {category} | {notes} |")
        
        lines.extend([
            "\n---",
            "\n## Security Considerations",
            "\n- Ensure all detected technologies are up-to-date with latest security patches",
            "- Review each component for known vulnerabilities (CVEs)",
            "- Minimize technology exposure to reduce attack surface",
            "- Implement security hardening for all detected frameworks",
            "\n---"
        ])
        
        return '\n'.join(lines)
    
    def _count_by_field(self, findings: List[Dict[str, Any]], field: str) -> Dict[str, int]:
        """Helper to count findings by a field value."""
        counts: Dict[str, int] = {}
        for finding in findings:
            value = finding.get(field, 'unknown').lower()
            counts[value] = counts.get(value, 0) + 1
        return counts
